name: Daily Site Rebuild

on:
  schedule:
    - cron: '0 22 * * *'  # Runs at 22:00 UTC, --> 00:00 CEST

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Create empty commit
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit --allow-empty -m "Trigger Rebuild"
          git push
